mavros_node:
  ros__parameters:
    fcu_url: "/dev/ttyUAB0:921600"
    gcs_url: ""
    tgt_system: 1
    fcu_protocol: "v2.0"
    tgt_component: 1
    heartbeat_rate: 1.0
    publish_sim_time: false

